worlds:
  canva:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'false'
    difficulty: PEACEFUL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'false'
    autoHeal: 'false'
    adjustSpawn: 'false'
    portalForm: ALL
    gameMode: ADVENTURE
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.5
      y: 40.0
      z: 0.5
      pitch: 90.0
      yaw: -0.009647191
    autoLoad: 'true'
    bedRespawn: 'false'
    worldBlacklist: []
    environment: NORMAL
    seed: '7669588083219252694'
    generator: VoidGen
    playerLimit: '-1'
    allowFlight: 'true'
